### ISSUE TITLE
querySampleType requiring write permissions

### ISSUE THREAD

**Issue by FaridW** [Telerik-Verified-Plugins/HealthKit#11]
Here is my prompt for permission code

`
window.plugins.healthkit.requestAuthorization({ 'readTypes'  : ['HKQuantityTypeIdentifierStepCount','HKQuantityTypeIdentifierActiveEnergyBurned'
]}, auth_callback, auth_callback);
`

And my query code:

`window.plugins.healthkit.querySampleType({'startDate': start, 'endDate': finish, 'sampleType': 'HKQuantityTypeIdentifierStepCount'}`

The authorisation dialogue appears with 2 toggles as expected initially, however the query code forces the authorisation dialogue again, with the 2 toggles maintaining their "on" stage, but also displays a prompt for write permission for the Identifier being requested (HKQuantityTypeIdentifierStepCount). I do not need write permission and do not explicitly request it in my code. The code I've shown is all the code my application contains that relates to this plugin.

Am I missing something obvious or is this unexpected behaviour?

**Comment by EddyVerbruggen** [comment]
Hi Farid,

Good point.

The plugin requests read and write permission because of a (in my opinion) flaw in the HealthKit SDK. If say you first request permission to read weight it will show the permission toggle for weight. Later if you ask write permission it will ONLY show the write toggle and you loose the read permission. If later you want to read again it asks for permission. Really crappy behavior imo.

To circumvent this and keep the API simply I've decided to always ask read and write permissions if you need at least one of those. I can however see why this could be suboptimal.

I think I'll add a `requestReadPermission` and `requireWritePermission` boolean to every API call, defaulting to `true` to remain backward compatible.

In the meanwhile you can use the `requestAuthorization` function before using the `querySampleType`. Just pass in only the correct read type and you should be able to use it like this (I have not tested this passing an empty `writeTypes` param, but I should work):

```js
function requestAuthorization() {
    window.plugins.healthkit.requestAuthorization(
        {
          // comma-separated type lists
          'readTypes'  : ['HKQuantityTypeIdentifierStepCount'],
          'writeTypes' : []
        },
        callback, // this is where you can use querySampleType
        callback
    );
  }
```

Let me know how this works out or you.

Thanks,
Eddy

**Comment by FaridW** [comment]
I've tried both omitting and including an empty array for writeTypes, the behaviour seems identical (permission prompt). 

I do actually have the requestAuthorization request on its own in one place (turning on HK integration), and also request authorization before querying the data.

I would be happy to look into this issue if you could give me some pointers regarding the codebase.

**Comment by EddyVerbruggen** [comment]
Hi, just checked. You'll get the permission prompt only for the read types if you do it like the example above (you can even leave out the `writeTypes` entirely).

If you're seeing a permission prompt for more options then please try deleting your app first as those permissions tend to accumulate (it shows any previously shown permission as well).

**Comment by EddyVerbruggen** [comment]
BAM! Then it he me. I was reading your bugreport wrong. You're saying that whatever read permission you ask upfront, the `querySampleType` function will always ask write permissions as well. That's a bug I will address.

**Comment by EddyVerbruggen** [comment]
Hi, version 0.3.0 is now available and should fix your trouble.

There's also the new `requestReadPermission` and `requestWritePermission` params for a few other methods, [see the docs](http://plugins.telerik.com/plugin/healthkit).

**Comment by FaridW** [comment]
Thank you Eddy, the updated version fixes the issue and I'm very pleased with how it's all working now.

If you ever need contributors to this plugin or another one please let me know, I'm keen to give back if I can help in any way :smile:

**Comment by EddyVerbruggen** [comment]
Great to hear! :+1:

And thanks for offer, I'll keep it in mind ;)

**Comment by pgmvyc** [comment]
Eddy, I am new to healthkit plugin. Trying to req the authorization like

  window.plugins.healthkit.requestAuthorization({
    "readTypes": ["HKCorrelationTypeIdentifierBloodPressure"], "writeTypes": []
  },
  function (value) {
    _trace("Access to HKCorrelationTypeIdentifierBloodPressure allowed", true);
  },
  function (value) {
    _trace("Access to HKCorrelationTypeIdentifierBloodPressure rejected", true);
  });

in the phonegap application.
The app does NOT display any dialogue but instead crashes 5-6 seconds later.
iOS8, the healthkit is available, 'healthkit' permission is on for the app in the Apple's settings.

Any hint on what I might be doing wrong ?

Thank you.
