### ISSUE TITLE
HKQuantityTypeIdentifierDietaryEnergyConsumed unit issue

### ISSUE THREAD

**Issue by kapilgwb** [Telerik-Verified-Plugins/HealthKit#39]
Hello,
I am using this function to save consume calorie in health kit

window.plugins.healthkit.saveQuantitySample(
                                                    {
                                                    'startDate': new Date(), // now
                                                    'endDate': new Date(), // now
                                                    'sampleType': HKQuantityTypeIdentifierDietaryEnergyConsumed,
                                                    'unit': unit,
                                                    'amount': qty
                                                    },
                                                    onSuccess,
                                                    onError
                                                    );

When i am passing unit "kcal"  and qty 56, then on health kit calorie is 56

But when i am passing unit "cal" and qty 56, then on health kit calorie is 0.056 (wrong)

And default unit in health kit is cal

Can you explain me what is wrong with this. this is health kit issue or plugin issue or my code issue.

**Comment by EddyVerbruggen** [comment]
Well actually (after some [research](https://en.wikipedia.org/?title=Calorie)) it turns out both the plugin and HealthKit itself are correct.

The Health app shows your entered data as '56 Cal' (capital 'C') which is according to Wikipedia (linked above) and [other sources](http://hyperphysics.phy-astr.gsu.edu/hbase/biology/kcal.html) equal to '56 kcal', whereas '56 Cal' is 1000 x '56 cal'.

I don't think things get any more confusing than this, have a nice day :+1:
