### ISSUE TITLE
Does the Telerik HealthKit plugin support the reproductive health data?

### ISSUE THREAD

**Issue by ElinaBS** [Telerik-Verified-Plugins/HealthKit#64]
Hi!

I would like to use this plugin for our app that analyzes women's reproductive health data to determine the fertility. However, I do not manage to read or write any of the reproductive health data, such as:

HKQuantityTypeIdentifierBasalBodyTemperature
or
HKCategoryTypeIdentifierMenstrualFlow

For the temperature I cannot get the unit right and for the menstrual flow it complains about the type. So I wonder if the reproductive health part of Health kit is supported at all in this plugin? In that case, how do I for instance specify the units for basal body temperature?

Thank you,
Elina

**Comment by EddyVerbruggen** [comment]
`` is [supported since iOS 9](https://developer.apple.com/reference/healthkit/hkcategorytypeidentifiermenstrualflow), on iOS 8 you'll get the 'unsupported type' message you've been probably seeing.

It can be queried using `querySampleType`:

```js
window.plugins.healthkit.querySampleType({
  'startDate': new Date(new Date().getTime() - 3 * 24 * 60 * 60 * 1000), // three days ago
  'endDate': new Date(), // now
  'sampleType': 'HKCategoryTypeIdentifierMenstrualFlow',
  'unit': 'count'
}, callback, callback);
```

To successfully query `HKQuantityTypeIdentifierBasalBodyTemperature` use the same example and swap these two properties in:

```js
  'sampleType': 'HKQuantityTypeIdentifierBasalBodyTemperature',
  'unit': 'degF' // or 'degC', for celcius
```
